export default {
    CREATE_MANAGER: "CREATE_MANAGER",
    CREATE_TENANT_OR_TECHNICIAN: "CREATE_TENANT_OR_TECHNICIAN",
    CREATE_DEPENDANT: "CREATE_DEPENDANT",
    LOAD_TENANTS_AND_TECHNICIANS: "LOAD_TENANTS_AND_TECHNICIANS",
}