export default {
    CREATE_MANAGER: "CREATE_MANAGER",
    CREATE_TENANT_OR_TECHNICIAN: "CREATE_TENANT_OR_TECHNICIAN",
    CREATE_DEPENDANT: "CREATE_DEPENDANT",
    LOAD_TENANTS_AND_TECHNICIANS: "LOAD_TENANTS_AND_TECHNICIANS",
    UPDATE_USER: "UPDATE_USER",
    DELETE_USER: "DELETE_USER",
    CREATE_ANNOUNCEMENT: "CREATE_ANNOUNCEMENT",
    UPDATE_ANNOUNCEMENT: "UPDATE_ANNOUNCEMENT",
    LOAD_ANNOUNCEMENTS: "LOAD_ANNOUNCEMENTS",
    LOAD_MANAGER_ANNOUNCEMENTS: "LOAD_MANAGER_ANNOUNCEMENTS",
    LOAD_TENANT_ANNOUNCEMENTS: "LOAD_TENANT_ANNOUNCEMENTS",
    DELETE_ANNOUNCEMENT: "DELETE_ANNOUNCEMENT",
}