const userGroups = {
    ROLE_USER: "ROLE_USER",
    ROLE_MANAGER: "ROLE_MANAGER",
    ROLE_TENANT: "ROLE_TENANT",
    ROLE_TECHNICIAN: "ROLE_TECHNICIAN",
    ROLE_ADMINISTRATOR: "ROLE_ADMINISTRATOR"
};

export default userGroups;
